# Generated by Django 3.0.7 on 2020-06-15 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toa', models.CharField(default='', max_length=50)),
                ('Adtitle', models.CharField(max_length=50)),
                ('bedroom', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('carpet_area', models.CharField(max_length=50)),
                ('floors', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('DOM', models.IntegerField()),
                ('S_desc', models.CharField(max_length=150)),
                ('img1', models.ImageField(upload_to=None)),
                ('img2', models.ImageField(upload_to=None)),
                ('img3', models.ImageField(default='', upload_to=None)),
                ('img4', models.ImageField(default='', upload_to=None)),
                ('img5', models.ImageField(default='', upload_to=None)),
                ('img6', models.ImageField(default='', upload_to=None)),
                ('img7', models.ImageField(default='', upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(default='', max_length=50)),
                ('Adtitle', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('DOM', models.IntegerField()),
                ('S_desc', models.CharField(max_length=150)),
                ('img1', models.ImageField(upload_to=None)),
                ('img2', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Freelance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tof', models.CharField(default='', max_length=50)),
                ('Adtitle', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('S_desc', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Furnitures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tof', models.CharField(default='', max_length=50)),
                ('Adtitle', models.CharField(max_length=50)),
                ('wood', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('DOM', models.IntegerField()),
                ('S_desc', models.CharField(max_length=150)),
                ('img1', models.ImageField(upload_to=None)),
                ('img2', models.ImageField(upload_to=None)),
                ('img3', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tov', models.CharField(default='', max_length=50)),
                ('Adtitle', models.CharField(default='', max_length=50)),
                ('brand', models.CharField(default='', max_length=50)),
                ('cost', models.IntegerField()),
                ('DOM', models.IntegerField()),
                ('S_desc', models.CharField(default='', max_length=150)),
                ('status', models.BooleanField(default=False)),
                ('img1', models.ImageField(blank=True, default='', upload_to='vehicles')),
                ('img2', models.ImageField(blank=True, default='', upload_to='vehicles')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
