# Generated by Django 3.0.7 on 2020-06-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='img1',
            field=models.ImageField(upload_to='vehicles'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='img2',
            field=models.ImageField(upload_to='vehicles'),
        ),
    ]
